# This is a basic workflow to help you get started with Actions

name: Package Module

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags: 
      - 'v*' # Include all tagged Versions starting with v
      - '!v*-*' # Exclude every Tags that has some string appended after the Version number

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Package Module
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      ModuleFileName: CharPDFExport.zip
      ManifestFileName: module.json
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2
  
      - name: Substitute Module Information
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/module.json'
        env:
          version: ${{steps.get_version.outputs.version-without-v}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/${{env.ManifestFileName}}
          download: https://github.com/${{github.repository}}/releases/download/${{steps.get_version.outputs.version}}/${{env.ModuleFileName}}
          readme: https://github.com/${{github.repository}}/blob/${{steps.get_version.outputs.version}}/README.md
          license: https://github.com/${{github.repository}}/blob/${{steps.get_version.outputs.version}}/LICENSE
          changelog: https://github.com/${{github.repository}}/blob/${{steps.get_version.outputs.version}}/CHANGELOG.md
          bugs: https://github.com/${{github.repository}}/issues

      # Runs a single command using the runners shell
      - name: Create Packages Module ZIP
        run: |
          cp README.md LICENSE src/
          zip -r ${{env.ModuleFileName}} ./src/*

      - name: Add Files to Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{steps.get_version.outputs.version}}
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: './src/${{env.ManifestFileName}}, ./${{env.ModuleFileName}}'
          tag: ${{ github.ref }}
